### PR TITLE
Migrate to Poetry+Conda

### PR DESCRIPTION
**Pull request by 0x2b3bfa0**
This pull request migrates from `setuptools` to [poetry](https://python-poetry.org/), leaving the virtual environment management to the `conda` ecosystem.

### CODE REVIEW

**Comment by SGenheden** [comment]
I like the spirt of this PR, thanks a lot for the work. 

Before I proceed, I have to investigate how this would work the internal CI/CD flow at AstraZeneca. 

In the mean time, here are a few questions for you:
* It seems that you need to clone the Git repository in order to install the package now. I see that as a huge drawback, as it adds another dependency on using the package. Many end-users are not familiar with Git usage.
* I haven't tested, but I guess these changes makes it impossible to install directly from the Git repo. With pip you can do `pip install git+url-to-git-repo` and it will clone and install the package from directly from git. 
* I understand what `poe` does, but for me it seems unnecessary to add an alias to `pytest`. 
* Why move the document source from `src` to `doc`?

**Comment by 0x2b3bfa0** [comment]
> _Before I proceed, I have to investigate how this would work the internal CI/CD flow at AstraZeneca._

External contributors are completely ignorant about your internal pipeline, and so do I. That's why I would recommend you to use GitHub Actions (like in #25 and #26) in the most [positively] boring and reproducible way.

> * _It seems that you need to clone the Git repository in order to install the package now. I see that as a huge drawback, as it adds another dependency on using the package. Many end-users are not familiar with Git usage._

Effectively, directly installing the package wouldn't be possible with the suggested changes, but restoring this functionality is a pull request away. We can also automate releases with `poetry build --format sdist` to keep the compatibility with the old install instructions.

> * _I haven't tested, but I guess these changes makes it impossible to install directly from the Git repo. With pip you can do pip install git+url-to-git-repo and it will clone and install the package from directly from git._

Yes, that wouldn't be possible anymore, though you can keep a separate orphan branch with the aforementioned `sdist` and synchronize it on push. 

> _I understand what poe does, but for me it seems unnecessary to add an alias to pytest._

The alias was only for consistency, but the main advantage of `poe` is on the documentation building part. While `poe test` is just a wrapper for `pytest`, `poe document` abstracts all the platform-dependent mechanism used for building the documentation. See #25 for an usage example, where documentation is automatically built and published on push with a GitHub Actions workflow.

Also, `poe` would enable you to define new useful commands in the future; I personally would put these in the roadmap, but it's a matter of taste:

* `poe format` for running both [`black`](https://github.com/psf/black) and [`isort`](https://pycqa.github.io/isort/) so people can commit clean code.
* `poe lint` for running [`flakehell`](https://github.com/life4/flakehell) without the test suite, leveraging the capabilities of the new `pyproject.toml` file.

> _Why move the document source from src to doc?_

I deemed the nesting unnecessary because the `source` directory wasn't needed anymore after removing the platform-specific build scripts: we aren't commiting the HTML artifacts to version control anyways; see #25.

**Before**
```
.
└── docs/
    ├── source/
    │   └── ...
    ├── make.bat
    └── Makefile
```

**After**
```
.
└── docs/
    └── ...
```

Both `Makefile` and `make.bat` have been replaced by a platform-independent `poe` command, so they aren't necessary anymore.

**Comment by SGenheden** [comment]
Thanks for the answers. And thanks for pushing this - I have really updated my knowledge on more modern dependency management these last couple of days, which is really much appreciated.

A realized and I have tested myself on private project of mine that pip is able to install "poetry managed" packages, which opens up a lot of possibilities for end-user that only really want to install the package, and for other packages that are dependent on this package. 

With this ability, you can:
* Install the package from a Github release
* Install the package directly from a git repository URL
* Install it when creating a conda environment by adding something like this to the end of the `environment.yml` file
```
- pip:
  - url-to-latest-release or url-to-git-repo
```

For developers, one would very much follow the path that you have outline in this PR:
1. clone the repository
2. install conda environment
3. install dependencies with poetry

I also realized that the latest conda version (I think it was added in 4.8.4) support creating an environment from a remote http url. That means that for end-user it would be sufficient to type the following line to install the entire package

```
conda env create --file url-to-environment.yml
````
if we in the `environment.yml` reference the latest Github release (see this example from my hobby project: https://github.com/SGenheden/auto-crop/blob/master/environment.yml)

But for users with old conda, we should perhaps provide instructions for how to do it the old way. 

So I will start from bottom-up and introduce poetry-support in the internal AstraZeneca repo and then release a new version on Github. At that point, we can catch up again and in particular have a look at the PRs for CI that you created, which I also very much like.

**Comment by 0x2b3bfa0** [comment]
😊  You're welcome!

> _I have really updated my knowledge on more modern dependency management these last couple of days [...]_

Me too, with your last comment. 🙃  I was looking a the problen from the least elegant angle.

> _A realized and I have tested myself on private project of mine that pip is able to install "poetry managed" packages, which opens up a lot of possibilities for end-user that only really want to install the package, and for other packages that are dependent on this package._

🤦 You're absolutely right! I forgot that PIP supports PEP-517 since 2019; my bad.

> _I also realized that the latest conda version (I think it was added in 4.8.4) support creating an environment from a remote http url._

I didn't know that, but it's definitely a game changer for easy installations.

> _So I will start from bottom-up and introduce poetry-support in the internal AstraZeneca repo and then release a new version on Github. At that point, we can catch up again and in particular have a look at the PRs for CI that you created, which I also very much like._

🎉  Excellent! Feel free to close this pull request then.

**Comment by SGenheden** [comment]
As of version 2.4.0, the content is included in the AiZynthFinder package. Hence, I reject this.

**Pull request closed without merging**
